export const EU_SYMBOL_SUFFIXES = ['.DE', '.F', '.MU', '.SG', '.HM', '.DU', '.BE'] as const;

export const GERMAN_EXCHANGE_CODES = [
  'XETRA',
  'GER',
  'FRA',
  'STU',
  'MUN',
  'HAM',
  'DUS',
  'BER',
  'SGT',
] as const;

export const US_TO_DE_MAPPING: Record<string, string[]> = {
  BABA: ['AHLA.DE', 'AHLA.F'],
  BIDU: ['B1C.DE', 'B1C.F'],
  JD: ['013A.DE', '013A.F'],
  NIO: ['NIO1.DE', 'NIO1.F'],
  GRAB: ['A6I.DE', 'A6I.F'],
  NVO: ['NOV.DE', 'NOVA.F'],
  ADUR: ['1N8.DE', '1N8.F'],
  HIMS: ['82W.DE', '82W.F', '82W.SG'],
  ONDS: ['6O9.DE', '6O9.F'],
  ASTS: ['AS5.DE', 'AS5.F'],
  OSCR: ['9VY.DE', '9VY.F'],
  PLTR: ['PTX.DE', 'PTX.F'],
  SOFI: ['4S0.DE', '4S0.F'],
  RIVN: ['1R1.DE', '1R1.F'],
  LCID: ['2LC.DE', '2LC.F'],
  HOOD: ['6HH.DE', '6HH.F'],
  COIN: ['1QZ.DE', '1QZ.F'],
  AFRM: ['5AF.DE', '5AF.F'],
  UPST: ['UP2.DE', 'UP2.F'],
  RKLB: ['RKLB.DE', 'RKLB.F'],
  SNOW: ['S4O.DE', 'S4O.F'],
  CRWD: ['C6R.DE', 'C6R.F'],
  DDOG: ['4DO.DE', '4DO.F'],
  NET: ['N3T.DE', 'N3T.F'],
  ZS: ['Z1S.DE', 'Z1S.F'],
  TTD: ['T2D.DE', 'T2D.F'],
  MARA: ['2M0.DE', '2M0.F'],
  RIOT: ['RIO1.DE', 'RIO1.F'],
  SMCI: ['0AI.DE', '0AI.F'],
  ABNB: ['6Z1.DE', '6Z1.F'],
  ACHR: ['AC7.DE', 'AC7.F'],
  ZETA: ['3ZT.DE', '3ZT.F'],
  ZVRA: ['4ZV.DE', '4ZV.F'],
  ASPN: ['2AP.DE', '2AP.F'],
  GRRR: ['1GR.DE', '1GR.F'],
  ONTO: ['0NT.DE', '0NT.F'],
  UNH: ['UNH.DE', 'UNH.F'],
  UPS: ['UPS.DE', 'UPS.F'],
  NKE: ['NKE.DE', 'NKE.F'],
  PYPL: ['2PP.DE', '2PP.F'],
  SHOP: ['SH0.DE', 'SH0.F'],
  TGT: ['TGT.DE', 'TGT.F'],
  PFE: ['PFE.DE', 'PFE.F'],
  OXY: ['OXY.DE', 'OXY.F'],
  ANF: ['ANF.DE', 'ANF.F'],
};

export const DE_TO_US_MAPPING: Record<string, string> = Object.fromEntries(
  Object.entries(US_TO_DE_MAPPING).flatMap(([usSymbol, germanListings]) =>
    germanListings.map((germanSymbol) => [germanSymbol.toUpperCase(), usSymbol]),
  ),
);
